import { useEffect, useRef, useState } from "react";
import { useLocation, useNavigate } from "react-router-dom";

import { ApiError } from "./api";
import { projectApi, requestId } from "./project-api";
import type { FormOptionsPayload, ProjectSummary, ScanEvent, SourceFile, ValidationPayload } from "./project-dto";
import { DRAFT_KEY, LoadingState, Metric, ProjectDraft, StatusPill, configFromDraft, draftFromProject, emptyDraft, formatBytes, scanMessage, statusTone, time, usePolling } from "./workbench-shared";

function DialogFrame({ title, description, children, footer, wide = false, alert = false, onClose }: { title: string; description: string; children: React.ReactNode; footer?: React.ReactNode; wide?: boolean; alert?: boolean; onClose?(): void }) {
  const navigate = useNavigate(); const location = useLocation(); const dialogRef = useRef<HTMLElement>(null); const close = () => { if (onClose) { onClose(); return; } const params = new URLSearchParams(location.search); params.delete("dialog"); params.delete("projectId"); navigate({ pathname: location.pathname, search: params.toString() }, { replace: true }); };
  useEffect(() => {
    const previous = document.activeElement as HTMLElement | null;
    const focusable = () => [...(dialogRef.current?.querySelectorAll<HTMLElement>('button:not([disabled]), a[href], input:not([disabled]), textarea:not([disabled]), select:not([disabled]), [tabindex]:not([tabindex="-1"])') ?? [])];
    window.setTimeout(() => focusable()[0]?.focus(), 0);
    const handler = (event: KeyboardEvent) => {
      if (event.key === "Escape") close();
      if (event.key !== "Tab") return;
      const items = focusable(); if (!items.length) return; const first = items[0]; const last = items.at(-1)!;
      if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last.focus(); }
      else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first.focus(); }
    };
    window.addEventListener("keydown", handler);
    return () => { window.removeEventListener("keydown", handler); previous?.focus(); };
  }, []); // eslint-disable-line react-hooks/exhaustive-deps
  return <div className="modal-backdrop"><section ref={dialogRef} className={`modal ${wide ? "wide" : ""}`} role={alert ? "alertdialog" : "dialog"} aria-modal="true" aria-labelledby="dialog-title"><header><div><span className="eyebrow">Venus 项目</span><h1 id="dialog-title">{title}</h1><p>{description}</p></div><button aria-label="关闭" className="modal-close" onClick={close}>×</button></header><div className="modal-body">{children}</div>{footer && <footer>{footer}</footer>}</section></div>;
}

export function NewProjectDialog({ notify }: { notify(message: string): void }) {
  const navigate = useNavigate(); const [step, setStep] = useState(1); const [options, setOptions] = useState<FormOptionsPayload | null>(null); const [draft, setDraft] = useState<ProjectDraft>(() => { try { const stored = localStorage.getItem(DRAFT_KEY); return stored ? { ...emptyDraft(), ...JSON.parse(stored) as ProjectDraft } : emptyDraft(); } catch { return emptyDraft(); } }); const [preview, setPreview] = useState<{ estimated_files: number; warnings: string[] } | null>(null); const [validation, setValidation] = useState<ValidationPayload | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const submitId = useRef(requestId("project-create"));
  useEffect(() => { const controller = new AbortController(); projectApi.formOptions(controller.signal).then((value) => { setOptions(value); setDraft((current) => ({ ...current, asrRef: current.asrRef || value.resources.find((item) => item.resource_type === "asr")?.resource_id || "", analysisRef: current.analysisRef || value.resources.find((item) => item.resource_type === "analysis")?.resource_id || "" })); }).catch((reason) => setError((reason as Error).message)); return () => controller.abort(); }, []);
  useEffect(() => { localStorage.setItem(DRAFT_KEY, JSON.stringify(draft)); submitId.current = requestId("project-create"); setValidation(null); }, [draft]);
  const update = <K extends keyof ProjectDraft>(key: K, value: ProjectDraft[K]) => setDraft((current) => ({ ...current, [key]: value })); const project = options ? { name: draft.name, description: draft.description, config: configFromDraft(draft, options.timezone) } : null;
  const next = async () => { if (step === 2 && draft.sourceDirectory) { try { const result = await projectApi.scanPreview(draft.sourceDirectory, draft.firstScanMode, draft.lookbackDays); setPreview({ estimated_files: result.processable_files, warnings: result.warnings }); } catch (reason) { setError((reason as Error).message); return; } } if (step === 3 && project) { try { setValidation(await projectApi.validate(project, "active")); } catch (reason) { setError((reason as Error).message); return; } } setError(""); setStep((value) => Math.min(4, value + 1)); };
  const submit = async (activation: "active" | "inactive") => { if (!project || busy) return; setBusy(true); setError(""); try { const result = await projectApi.create(submitId.current, project, activation); localStorage.removeItem(DRAFT_KEY); notify(result.initial_scan?.status === "failed" ? `项目已创建，但首次扫描失败：${result.initial_scan.error_summary ?? "请查看项目状态"}` : "项目已创建"); navigate(`/projects/${result.project.project_id}`, { replace: true }); } catch (reason) { const apiError = reason as ApiError; setError(apiError.message); if (apiError.code === "request_id_conflict") submitId.current = requestId("project-create"); } finally { setBusy(false); } };
  const blockers = validation?.blockers ?? []; const fatal = validation?.fatal ?? []; const warnings = validation?.warnings ?? []; const migrationBlocked = options?.data_mode === "legacy";
  return <DialogFrame wide title="新建项目" description={`第 ${step} 步，共 4 步 · ${["基本信息", "扫描设置", "处理与输出", "确认配置"][step - 1]}`} footer={<><button className="button" disabled={step === 1 || busy} onClick={() => setStep((value) => value - 1)}>上一步</button><span className="footer-spacer" />{step < 4 ? <button className="button primary" disabled={migrationBlocked || !canContinue(step, draft) || busy} onClick={() => void next()}>下一步</button> : <><button className="button" disabled={migrationBlocked || busy || fatal.length > 0} onClick={() => void submit("inactive")}>保存为未启用</button><button className="button primary" disabled={migrationBlocked || busy || fatal.length > 0 || blockers.length > 0} onClick={() => void submit("active")}>{busy ? "创建中…" : "创建并启用"}</button></>}</>}>
    <ol className="stepper">{[1,2,3,4].map((value) => <li className={value === step ? "active" : value < step ? "done" : ""} key={value}><span>{value < step ? "✓" : value}</span></li>)}</ol>{error && <p className="form-error" role="alert">{error}</p>}{migrationBlocked && <p className="form-error" role="alert">旧版数据尚未完成迁移确认，暂时不能创建项目。</p>}{!options ? <LoadingState /> : <>
      {step === 1 && <div className="form-grid"><Field label="项目名称" required><input autoFocus value={draft.name} maxLength={80} onChange={(event) => update("name", event.target.value)} /></Field><Field label="项目描述"><textarea value={draft.description} onChange={(event) => update("description", event.target.value)} /></Field><FolderField label="录像目录" value={draft.sourceDirectory} onChange={(value) => update("sourceDirectory", value)} /></div>}
      {step === 2 && <div className="form-grid"><Field label="首次扫描"><select value={draft.firstScanMode} onChange={(event) => update("firstScanMode", event.target.value as ProjectDraft["firstScanMode"])}><option value="new_only">只处理创建后新增录像</option><option value="recent">回溯最近录像</option><option value="choose_existing">创建后手动选择已有录像</option></select></Field>{draft.firstScanMode === "recent" && <Field label="回溯范围"><select value={draft.lookbackDays} onChange={(event) => update("lookbackDays", Number(event.target.value) as ProjectDraft["lookbackDays"])}>{options.lookback_days.map((days) => <option value={days} key={days}>最近 {days} 天</option>)}</select></Field>}<label className="toggle-field"><input type="checkbox" checked={draft.scheduleEnabled} onChange={(event) => update("scheduleEnabled", event.target.checked)} /><span><strong>定时扫描</strong><small>关闭时仍可随时手动扫描</small></span></label>{draft.scheduleEnabled && <><Field label="扫描频率"><select value={draft.scheduleMode} onChange={(event) => update("scheduleMode", event.target.value as ProjectDraft["scheduleMode"])}><option value="daily">每天固定时间</option><option value="interval">按时间间隔</option></select></Field>{draft.scheduleMode === "daily" ? <Field label="每天时间"><input type="time" value={draft.dailyTime} onChange={(event) => update("dailyTime", event.target.value)} /></Field> : <Field label="扫描间隔"><select value={draft.intervalMinutes} onChange={(event) => update("intervalMinutes", Number(event.target.value) as ProjectDraft["intervalMinutes"])}>{options.interval_minutes.map((minutes) => <option value={minutes} key={minutes}>每 {minutes} 分钟</option>)}</select></Field>}</>}{preview && <div className="preview-card"><strong>预计可创建 {preview.estimated_files} 条剪辑记录</strong>{preview.warnings.map((warning) => <p key={warning}>{warning}</p>)}</div>}</div>}
      {step === 3 && <div className="form-grid two"><Field label="ASR 资源"><select value={draft.asrRef} onChange={(event) => update("asrRef", event.target.value)}>{options.resources.filter((item) => item.resource_type === "asr").map((item) => <option value={item.resource_id} key={item.resource_id}>{item.display_name} · {item.ready ? "已就绪" : "不可用"}</option>)}</select></Field><Field label="分析资源"><select value={draft.analysisRef} onChange={(event) => update("analysisRef", event.target.value)}>{options.resources.filter((item) => item.resource_type === "analysis").map((item) => <option value={item.resource_id} key={item.resource_id}>{item.display_name} · {item.ready ? "已就绪" : "不可用"}</option>)}</select></Field><FolderField label="成片输出目录" value={draft.outputDirectory} onChange={(value) => update("outputDirectory", value)} /><Field label="中间产物保留"><select value={draft.retention} onChange={(event) => update("retention", event.target.value as ProjectDraft["retention"])}><option value="remind_immediately">完成后立即提醒清理</option><option value="remind_after_7_days">完成 7 天后提醒清理</option><option value="keep">始终保留</option></select></Field><p className="retention-note">原始录像永不自动删除；成片始终保留。</p></div>}
      {step === 4 && <div className="summary-step"><IssueGroup title="必须修正" tone="error" issues={fatal} /><IssueGroup title="启用前需处理" tone="warning" issues={blockers} /><IssueGroup title="提醒" tone="info" issues={warnings} />{!fatal.length && !blockers.length && <div className="readiness success"><StatusPill status="idle" label="可以运行" /><div><strong>所有必要配置均已就绪</strong><p>创建并启用后，项目会按当前扫描设置开始工作。</p></div></div>}<dl className="summary-list"><div><dt>项目</dt><dd>{draft.name}</dd><small>{draft.sourceDirectory}</small></div><div><dt>扫描</dt><dd>{draft.scheduleEnabled ? "定时 + 手动" : "仅手动扫描"}</dd><small>{draft.firstScanMode === "recent" ? `首次回溯 ${draft.lookbackDays} 天` : draft.firstScanMode === "choose_existing" ? "创建后选择已有录像" : "仅处理新录像"}</small></div><div><dt>输出</dt><dd>{draft.outputDirectory}</dd><small>原始录像永不自动删除</small></div></dl></div>}
    </>}</DialogFrame>;
}

function canContinue(step: number, draft: ProjectDraft) { if (step === 1) return Boolean(draft.name.trim() && draft.sourceDirectory.trim()); if (step === 3) return Boolean(draft.asrRef && draft.analysisRef && draft.outputDirectory.trim()); return true; }
function Field({ label, required, children }: { label: string; required?: boolean; children: React.ReactNode }) { return <label className="field"><span>{label}{required && <b> *</b>}</span>{children}</label>; }
function FolderField({ label, value, onChange }: { label: string; value: string; onChange(value: string): void }) { const choose = async () => { const selected = await window.liveClipperShell?.selectFolder?.(`选择${label}`); if (selected) onChange(selected); }; return <Field label={label} required><div className="input-action"><input value={value} onChange={(event) => onChange(event.target.value)} placeholder="选择本机绝对路径" />{window.liveClipperShell?.selectFolder && <button className="button" onClick={() => void choose()} type="button">选择…</button>}</div></Field>; }
function IssueGroup({ title, tone, issues }: { title: string; tone: string; issues: Array<{ field: string; message: string }> }) { if (!issues.length) return null; return <div className={`issue-group ${tone}`} role={tone === "error" ? "alert" : undefined}><strong>{title}</strong>{issues.map((issue) => <p key={`${issue.field}-${issue.message}`}>{issue.message}</p>)}</div>; }

export function ProjectSettingsDialog({ project, onSaved }: { project: ProjectSummary; onSaved(): Promise<void> }) {
  const navigate = useNavigate(); const [draft, setDraft] = useState(() => draftFromProject(project)); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const id = useRef(requestId("project-update")); const config = project.config!.config;
  const save = async () => { setBusy(true); setError(""); try { await projectApi.update(project.project_id, id.current, project.current_config_revision, { name: draft.name, description: draft.description, config: configFromDraft(draft, config.schedule.timezone) }); await onSaved(); navigate(`/projects/${project.project_id}`, { replace: true }); } catch (reason) { setError((reason as Error).message); } finally { setBusy(false); } };
  return <DialogFrame title="项目设置" description="更改仅影响后续扫描和新建的剪辑记录。" footer={<><span className="footer-spacer" /><button className="button primary" disabled={busy || !draft.name.trim()} onClick={() => void save()}>{busy ? "保存中…" : "保存设置"}</button></>}><div className="form-grid two">{error && <p className="form-error" role="alert">{error}</p>}<Field label="项目名称"><input value={draft.name} onChange={(event) => setDraft({ ...draft, name: event.target.value })} /></Field><Field label="项目描述"><textarea value={draft.description} onChange={(event) => setDraft({ ...draft, description: event.target.value })} /></Field><FolderField label="录像目录" value={draft.sourceDirectory} onChange={(value) => setDraft({ ...draft, sourceDirectory: value })} /><FolderField label="输出目录" value={draft.outputDirectory} onChange={(value) => setDraft({ ...draft, outputDirectory: value })} /><label className="toggle-field"><input type="checkbox" checked={draft.scheduleEnabled} onChange={(event) => setDraft({ ...draft, scheduleEnabled: event.target.checked })} /><span><strong>定时扫描</strong><small>手动扫描始终可用</small></span></label>{draft.scheduleEnabled && <><Field label="频率"><select value={draft.scheduleMode} onChange={(event) => setDraft({ ...draft, scheduleMode: event.target.value as ProjectDraft["scheduleMode"] })}><option value="daily">每天固定时间</option><option value="interval">按时间间隔</option></select></Field>{draft.scheduleMode === "daily" ? <Field label="每天时间"><input type="time" value={draft.dailyTime} onChange={(event) => setDraft({ ...draft, dailyTime: event.target.value })} /></Field> : <Field label="扫描间隔"><select value={draft.intervalMinutes} onChange={(event) => setDraft({ ...draft, intervalMinutes: Number(event.target.value) as ProjectDraft["intervalMinutes"] })}><option value="30">每 30 分钟</option><option value="60">每 1 小时</option><option value="180">每 3 小时</option><option value="360">每 6 小时</option><option value="720">每 12 小时</option></select></Field>}</>}</div></DialogFrame>;
}

export function LatestScanDialog({ project }: { project: ProjectSummary }) {
  const state = usePolling((signal) => projectApi.latestScan(project.project_id, signal), project.latest_scan?.status === "running" ? 5000 : 15000); const scan = state.data?.scan ?? project.latest_scan;
  return (
    <DialogFrame title="最近扫描结果" description={`${project.name} · 扫描不会重复创建剪辑记录。`}>
      {!scan ? <p className="quiet-state">这个项目还没有扫描记录。</p> : (
        <>
          <div className={`readiness ${statusTone(scan.status)}`}>
            <StatusPill status={scan.status} label={scan.status === "partial" ? "部分完成" : scan.status === "success" ? "已完成" : undefined} />
            <div><strong>{scanMessage(scan)}</strong><p>{scan.trigger_source === "scheduled" ? "定时触发" : "手动触发"} · {time(scan.completed_at ?? scan.started_at)}</p></div>
          </div>
          <div className="scan-stats"><Metric label="新建记录" value={scan.created_count ?? 0} /><Metric label="已存在" value={scan.duplicate_count ?? 0} /><Metric label="仍在写入" value={scan.unstable_count ?? 0} /><Metric label="不支持" value={scan.unsupported_count ?? 0} /><Metric label="范围外" value={scan.excluded_count ?? 0} /><Metric label="失败" value={scan.failed_count ?? 0} tone="error" /></div>
          {scan.error_summary && <p className="form-error" role="alert">{scan.error_summary}</p>}
        </>
      )}
    </DialogFrame>
  );
}

export function ChooseRecordingsDialog({ project, onScanned }: { project: ProjectSummary; onScanned(scan: ScanEvent): Promise<void> }) {
  const navigate = useNavigate(); const [files, setFiles] = useState<SourceFile[]>([]); const [selected, setSelected] = useState<string[]>([]); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const id = useRef(requestId("scan-selected"));
  useEffect(() => { const controller = new AbortController(); projectApi.sourceFiles(project.project_id, controller.signal).then((result) => setFiles(result.files)).catch((reason) => setError((reason as Error).message)); return () => controller.abort(); }, [project.project_id]);
  const scan = async () => { if (!selected.length || busy) return; setBusy(true); try { const result = await projectApi.scan(project.project_id, id.current, "selected", selected); await onScanned(result.scan); navigate(`/projects/${project.project_id}`, { replace: true }); } catch (reason) { setError((reason as Error).message); } finally { setBusy(false); } };
  return <DialogFrame wide title="选择已有录像" description="只会提交当前勾选且可处理的相对路径。" footer={<><span>{selected.length} 个已选择</span><span className="footer-spacer" /><button className="button primary" disabled={!selected.length || busy} onClick={() => void scan()}>{busy ? "扫描中…" : "扫描所选录像"}</button></>}>{error && <p className="form-error" role="alert">{error}</p>}<div className="source-files">{files.map((file) => <label className={!file.selectable ? "disabled" : ""} key={file.relative_path}><input type="checkbox" disabled={!file.selectable} checked={selected.includes(file.relative_path)} onChange={(event) => setSelected((current) => event.target.checked ? [...current, file.relative_path] : current.filter((item) => item !== file.relative_path))} /><span><strong>{file.relative_path}</strong><small>{formatBytes(file.bytes)} · {time(file.modified_at)}{file.reason ? ` · ${file.reason}` : ""}</small></span></label>)}{!files.length && !error && <LoadingState />}</div></DialogFrame>;
}

export function PauseProjectDialog({ projectName, onClose, onConfirm }: { projectName: string; onClose(): void; onConfirm(): Promise<boolean> }) {
  const [busy, setBusy] = useState(false);
  const confirm = async () => { if (busy) return; setBusy(true); const succeeded = await onConfirm(); setBusy(false); if (succeeded) onClose(); };
  return <DialogFrame alert title="暂停项目" description={`确认暂停“${projectName}”的自动扫描？`} onClose={onClose} footer={<><button className="button" disabled={busy} onClick={onClose}>取消</button><span className="footer-spacer" /><button className="button primary" disabled={busy} onClick={() => void confirm()}>{busy ? "暂停中…" : "确认暂停"}</button></>}><div className="readiness warning"><StatusPill status="paused" label="暂停自动扫描" /><div><strong>已有工作会继续，手动扫描仍可用</strong><p>暂停只会停止后续自动扫描，不会中断正在处理或排队的剪辑记录。</p></div></div></DialogFrame>;
}
