import { useCallback, useEffect, useState } from "react";
import { Link, useLocation, useNavigate, useParams, useSearchParams } from "react-router-dom";

import { ChooseRecordingsDialog, LatestScanDialog, PauseProjectDialog, ProjectSettingsDialog } from "./ProjectDialogs";
import { projectApi, requestId } from "./project-api";
import type { Run, RunFilter } from "./project-dto";
import { ErrorState, LoadingState, Metric, PageHeading, RUN_LABELS, RunCard, STAGES, STATUS_LABELS, SectionHeading, StatusPill, basename, scanMessage, time, usePolling } from "./workbench-shared";

export function ProjectPage({ notify }: { notify(message: string): void }) {
  const { projectId = "" } = useParams(); const navigate = useNavigate(); const location = useLocation(); const [params] = useSearchParams();
  const projectState = usePolling((signal) => projectApi.project(projectId, signal), 15000, projectId);
  const [filter, setFilter] = useState<RunFilter>("all"); const [runs, setRuns] = useState<Run[]>([]); const [cursor, setCursor] = useState<string | null>(null); const [hasMore, setHasMore] = useState(false); const [runsError, setRunsError] = useState(""); const [loadingRuns, setLoadingRuns] = useState(true); const [scanBusy, setScanBusy] = useState(false); const [pauseOpen, setPauseOpen] = useState(false);
  const loadRuns = useCallback(async (append = false, nextCursor = cursor) => { setLoadingRuns(true); try { const payload = await projectApi.runs(projectId, filter, append ? nextCursor : null); setRuns((current) => append ? [...current, ...payload.runs] : payload.runs); setCursor(payload.cursor); setHasMore(payload.has_more); setRunsError(""); } catch (error) { setRunsError((error as Error).message); } finally { setLoadingRuns(false); } }, [cursor, filter, projectId]);
  useEffect(() => { setCursor(null); void loadRuns(false, null); }, [filter, projectId]); // eslint-disable-line react-hooks/exhaustive-deps
  const project = projectState.data?.project; const active = Boolean(project && (project.workload.processing || project.workload.queued || project.latest_scan?.status === "running"));
  useEffect(() => { if (!active) return; const id = window.setInterval(() => { if (!document.hidden) { void projectState.refresh(); void loadRuns(false, null); } }, 5000); return () => window.clearInterval(id); }, [active, loadRuns, projectState.refresh]);
  if (projectState.loading && !project) return <LoadingState />;
  if (!project) return projectState.error.includes("不存在") ? <ObjectNotFound type="项目" /> : <ErrorState message={projectState.error} retry={() => void projectState.refresh()} />;
  const openDialog = (dialog: string) => navigate({ pathname: location.pathname, search: new URLSearchParams({ dialog, projectId }).toString() });
  const doScan = async () => { if (scanBusy) return; setScanBusy(true); try { const result = await projectApi.scan(projectId, requestId("scan"), "new"); notify(scanMessage(result.scan)); await Promise.all([projectState.refresh(), loadRuns(false, null)]); openDialog("latest-scan"); } catch (error) { notify((error as Error).message); } finally { setScanBusy(false); } };
  const activate = async (action: "enable" | "pause" | "resume") => { try { await projectApi.activate(projectId, action, requestId(`project-${action}`)); notify(action === "pause" ? "项目已暂停；已有剪辑记录会继续处理，手动扫描仍可用" : action === "resume" ? "项目已恢复运行" : "项目已启用"); await projectState.refresh(); return true; } catch (error) { notify((error as Error).message); return false; } };
  const activationAction = project.activation_state === "paused" ? "resume" : "enable";
  return <section className="page project-detail"><div className="breadcrumbs"><Link to="/projects">项目</Link><span>›</span><span>{project.name}</span></div><PageHeading eyebrow="项目详情" title={project.name} description={project.description || "这条生产线还没有描述。"} actions={<><button className="button" onClick={() => openDialog("project-settings")}>项目设置</button><button className="button" onClick={() => project.activation_state === "active" ? setPauseOpen(true) : void activate(activationAction)}>{project.activation_state === "active" ? "暂停项目" : project.activation_state === "paused" ? "恢复项目" : "启用项目"}</button><button className="button primary" disabled={scanBusy || project.latest_scan?.status === "running" || project.readiness_state === "blocked"} onClick={() => void doScan()}>{scanBusy || project.latest_scan?.status === "running" ? "扫描中…" : "手动扫描"}</button></>} />
    {projectState.error && <p className="stale-warning" role="alert">刷新失败：{projectState.error}。正在保留上次成功数据。</p>}{project.blocking_issues.map((issue) => <div className="project-alert error" role="alert" key={issue.code}><strong>项目需要处理</strong><p>{issue.message}</p></div>)}
    <div className="project-overview"><div className="hero-status"><StatusPill status={project.main_status} /><h2>{STATUS_LABELS[project.main_status] ?? "未知状态"}</h2><p>{project.current_run ? `当前：${basename(project.current_run.latest_seen_path)}` : project.activation_state === "paused" ? "自动扫描已暂停；已有记录继续处理。" : "当前没有正在处理的剪辑记录。"}</p></div><div className="metric-grid"><Metric label="处理中" value={project.workload.processing} /><Metric label="排队" value={project.workload.queued} /><Metric label="待审" value={project.workload.awaiting_review} /><Metric label="失败" value={project.workload.failed} tone="error" /><Metric label="已完成" value={project.workload.completed} /></div></div>
    <div className="project-meta-grid"><article><span>扫描方式</span><strong>{project.schedule?.enabled ? "定时 + 手动扫描" : "仅手动扫描"}</strong><small>{project.schedule?.enabled ? `下次 ${time(project.schedule.next_scan_at)}` : "手动扫描始终可用"}</small></article><article><span>最近扫描</span><strong>{project.latest_scan ? scanMessage(project.latest_scan) : "尚未扫描"}</strong>{project.latest_scan && <button className="text-button" onClick={() => openDialog("latest-scan")}>查看结果</button>}</article><article><span>录像目录</span><strong title={project.config?.config.source.directory}>{project.config ? basename(project.config.config.source.directory) : "—"}</strong>{project.config?.config.source.first_scan_mode === "choose_existing" && <button className="text-button" onClick={() => openDialog("choose-recordings")}>选择已有录像</button>}</article></div>
    <section className="runs-section"><SectionHeading title="剪辑记录" subtitle="按真实运行状态查看这条生产线的工作" /><div className="filters" role="tablist" aria-label="剪辑记录筛选">{([['all','全部'],['active','进行中'],['attention','需处理'],['completed','已完成']] as Array<[RunFilter,string]>).map(([value,label]) => <button role="tab" aria-selected={filter === value} className={filter === value ? "active" : ""} onClick={() => setFilter(value)} key={value}>{label}</button>)}</div>{runsError && <p className="stale-warning" role="alert">刷新失败：{runsError}。正在保留上次成功数据。</p>}<div className="runs-list">{runs.map((run) => <RunCard key={run.run_id} run={run} project={project} />)}{!runs.length && !loadingRuns && <p className="quiet-state">这个筛选下还没有剪辑记录。</p>}</div>{hasMore && <button className="button load-more" disabled={loadingRuns} onClick={() => void loadRuns(true, cursor)}>{loadingRuns ? "加载中…" : "加载更多"}</button>}</section>
    {params.get("dialog") === "project-settings" && <ProjectSettingsDialog project={project} onSaved={async () => { await projectState.refresh(); notify("项目设置已保存"); }} />}{params.get("dialog") === "latest-scan" && <LatestScanDialog project={project} />}{params.get("dialog") === "choose-recordings" && <ChooseRecordingsDialog project={project} onScanned={async (scan) => { notify(scanMessage(scan)); await Promise.all([projectState.refresh(), loadRuns(false, null)]); }} />}{pauseOpen && <PauseProjectDialog projectName={project.name} onClose={() => setPauseOpen(false)} onConfirm={() => activate("pause")} />}
  </section>;
}

export function RunPage() {
  const { projectId = "", runId = "" } = useParams(); const state = usePolling(async (signal) => { const [run, project] = await Promise.all([projectApi.run(runId, signal), projectApi.project(projectId, signal)]); return { ...run, project: project.project }; }, 15000, `${projectId}:${runId}`); const active = state.data?.run.status === "processing" || state.data?.run.status === "queued";
  useEffect(() => { if (!active) return; const id = window.setInterval(() => { if (!document.hidden) void state.refresh(); }, 5000); return () => window.clearInterval(id); }, [active, state.refresh]);
  if (state.loading && !state.data) return <LoadingState />;
  if (!state.data) return state.error.includes("不存在") ? <ObjectNotFound type="剪辑记录" /> : <ErrorState message={state.error} retry={() => void state.refresh()} />;
  const { run, stage_events: events, project } = state.data; const currentIndex = run.current_stage ? STAGES.findIndex(([stage]) => stage === run.current_stage) : run.status === "completed" ? STAGES.length : -1;
  return <section className="page run-detail"><div className="breadcrumbs"><Link to="/projects">项目</Link><span>›</span><Link to={`/projects/${projectId}`}>{project.name}</Link><span>›</span><span>{basename(run.latest_seen_path)}</span></div><PageHeading eyebrow="剪辑记录" title={basename(run.latest_seen_path)} description={`${project.name} · 创建于 ${time(run.queued_at)}`} actions={<>{run.status === "awaiting_review" && <Link className="button" to="/review">进入待审</Link>}<StatusPill status={run.status} label={run.status === "queued" && run.queue_position ? `队列第 ${run.queue_position} 位` : RUN_LABELS[run.status]} /></>} />{state.error && <p className="stale-warning" role="alert">刷新失败：{state.error}。正在保留上次成功数据。</p>}{run.error_summary && <div className="project-alert error" role="alert"><strong>处理已中断</strong><p>{run.error_summary}</p><small>{run.error_code}</small></div>}<section className="stage-rail" aria-label="处理阶段">{STAGES.map(([stage, label], index) => <div className={index < currentIndex || run.status === "completed" ? "done" : index === currentIndex ? "current" : "pending"} key={stage}><span>{index < currentIndex || run.status === "completed" ? "✓" : index + 1}</span><strong>{label}</strong></div>)}</section><div className="run-detail-grid"><article><span>来源路径</span><strong title={run.latest_seen_path}>{run.latest_seen_path}</strong></article><article><span>触发来源</span><strong>{run.trigger_source === "scheduled" ? "定时扫描" : "手动扫描"}</strong></article><article><span>配置版本</span><strong>第 {run.config_revision} 版</strong></article><article><span>最后更新</span><strong>{time(run.updated_at)}</strong></article></div><section className="section-block"><SectionHeading title="参数快照" subtitle="创建这条剪辑记录时冻结的处理参数" /><pre className="parameter-snapshot">{JSON.stringify(run.parameter_snapshot, null, 2)}</pre></section><section className="section-block"><SectionHeading title="阶段事件" subtitle="这条记录在六阶段流程中的真实事件" /><div className="timeline">{events.map((event) => <div key={event.event_id}><span>{time(event.occurred_at)}</span><strong>{STAGES.find(([stage]) => stage === event.stage)?.[1] ?? event.stage}</strong><small>{event.event_type}</small></div>)}{!events.length && <p className="quiet-state">尚无阶段事件。</p>}</div></section></section>;
}

export function ObjectNotFound({ type }: { type: string }) { return <section className="page"><div className="empty-state"><strong>{type}不存在</strong><p>它可能已被移除，或链接中的标识不正确。</p><Link className="button primary" to="/projects">返回项目</Link></div></section>; }
