import { Field } from '@astryxdesign/core/Field';
import { FormLayout } from '@astryxdesign/core/FormLayout';
import { TextInput } from '@astryxdesign/core/TextInput';
import { Selector } from '@astryxdesign/core/Selector';
import { NumberInput } from '@astryxdesign/core/NumberInput';
import { CheckboxInput } from '@astryxdesign/core/CheckboxInput';
import { Button } from '@astryxdesign/core/Button';
import { useEffect, useId, useRef, useState } from 'react';
import { Link, useLocation, useNavigate, useBlocker, useBeforeUnload } from 'react-router-dom';
import { api, post, ApiError } from './api';
import { requestId } from './project-api';
import { DialogFrame } from './ProjectDialogs';
import { ErrorState, LoadingState, PageHeading, usePolling } from './workbench-shared';

type Kind = 'ai' | 'local_asr' | 'cloud_asr' | 'local_agent';
type Purpose = 'asr' | 'analysis' | 'review';
type Config = { model?: string; endpoint?: string; provider?: string; region?: string; workspace?: string; model_source?: string; language?: string; purposes: Purpose[]; [key: string]: unknown };
type Proposal = { name: string; kind: Kind; config: Config };
export type Resource = Proposal & { model_files?: { state: string; installed_bytes: number; partial_bytes: number; bytes_downloaded: number; bytes_total: number; last_error?: string; job_id?: string }; preparation?: { id: string; status: string }; resource_id: string; revision: number; ready: boolean; deleted: boolean; has_credential: boolean; state: string; validation: Record<string, { state: string; code: string; checked_at?: string }>; projects: Array<{ project_id: string; name: string; purposes: Purpose[] }>; active_runs: Array<{ run_id: string; project_id: string; status: string }>; failed_runs: Array<{ run_id: string; project_id: string; status: string }> };
const purposes: Record<Purpose, string> = { asr: '语音识别', analysis: '内容分析', review: 'AI 审阅' };
const kinds: Record<Kind, string> = { local_asr: '本机语音识别', cloud_asr: '云端语音识别', ai: 'AI 模型', local_agent: 'Claude Code 本地审阅' };
const states: Record<string, string> = { pending: '待准备', preparing: '准备中', ready: '可用', needs_repair: '需要修复' };
const validationMessages: Record<string, string> = {
  credential_invalid: '凭据无效，请核对账号与密钥', credential_unavailable: '凭据不可用，请修复原账号密钥',
  permission_or_quota: '额度或权限不足，请到服务商核对', rate_limited: '请求受限，请稍后手动验证',
  connection_timeout: '连接超时，请检查网络和服务地址', result_unknown: '请求结果未知，请先核对原操作',
  model_not_found: '模型不存在或账号无权访问，请核对模型标识', parameter_unsupported: '服务不接受当前参数，请按服务商文档调整',
  output_format_invalid: '返回格式不符合用途要求，请检查模型能力', analysis_output_invalid: '分析输出不符合要求',
  correction_output_invalid: '文字校对输出不符合要求', capability_validation_failed: '用途验证未通过，请检查模型与运行环境',
  model_not_installed: '模型尚未完整安装，请准备模型', ai_resource_unavailable: '审阅接入不可用，请检查 Claude Code 登录状态',
};
function validationMessage(code: string) { return code ? validationMessages[code] || '验证未通过，请检查配置和模型能力' : ''; }
const empty = (): Proposal => ({ name: '', kind: 'ai', config: { provider: '', model: '', purposes: ['analysis', 'review'] } });
type SavedDraft = { proposal: Proposal; revision?: number; operation?: string; validationOperation?: string };
const readDraft = (key: string): SavedDraft | null => { try { return JSON.parse(localStorage.getItem(key) || 'null') as SavedDraft | null; } catch { return null; } };

export function resourceReturn(search: string, resource?: Resource): string | null {
  const query = new URLSearchParams(search); const origin = query.get('origin'); const project = query.get('project'); const purpose = query.get('purpose');
  if (!purpose || !(purpose in purposes)) return null;
  if (origin === 'onboarding') { const next = new URLSearchParams({ resourcePurpose: purpose }); if (resource && resource.config.purposes.includes(purpose as Purpose)) next.set('selectedResource', resource.resource_id); return `/studio?${next}`; }
  if (origin !== 'new-project' && (origin !== 'project' || !project || !/^[A-Za-z0-9_-]+$/.test(project))) return null;
  const next = new URLSearchParams({ dialog: origin === 'new-project' ? 'new-project' : 'project-settings', resourcePurpose: purpose });
  const sourceDraft = query.get('sourceDraft'); if (origin === 'new-project' && sourceDraft && /^[A-Za-z0-9_-]+$/.test(sourceDraft)) next.set('draft', sourceDraft);
  if (resource && resource.config.purposes.includes(purpose as Purpose)) next.set('selectedResource', resource.resource_id);
  return `${origin === 'new-project' ? '/projects' : `/projects/${project}`}?${next}`;
}

export function ResourcesPage() {
  const location = useLocation(); const parts = location.pathname.split('/').filter(Boolean);
  if (parts[1] === 'new') return <ResourceEditor key={location.pathname + location.search} />;
  if (parts[1] && parts[2] === 'edit') return <ResourceEditor key={location.pathname + location.search} resourceId={parts[1]} />;
  if (parts[1]) return <ResourceDetail resourceId={parts[1]} />;
  return <ResourceList />;
}

function ResourceList() {
  const state = usePolling((signal) => api<{ resources: Resource[]; migration: string; cleanups: Array<{ request_id: string; resource_id: string }> }>('/api/resources', {}, signal), 15000, 'resources');
  const [actionError, setActionError] = useState(''); const [search, setSearch] = useState(''); const [purpose, setPurpose] = useState(''); const [status, setStatus] = useState('');
  if (!state.data) return state.loading ? <LoadingState /> : <ErrorState message={state.error} retry={() => void state.refresh()} />;
  const filtered = state.data.resources.filter(r => `${r.name} ${r.config.model || ''}`.toLowerCase().includes(search.toLowerCase()) && (!purpose || r.config.purposes.includes(purpose as Purpose)) && (!status || r.state === status || Object.values(r.validation).some(v => v.state === status)));
  return <section className="page resources-page"><PageHeading title="资源" description="管理语音识别和 AI 资源，为项目选择合适的模型。" actions={<Button  label={"添加资源"} variant="primary" href={"/resources/new"} as={ResourceLink} />} />
    {actionError && <p role="alert">{actionError}</p>}{state.error && <p role="alert">刷新失败，显示的是上次读取结果。{state.error}</p>}
    {state.data.migration !== 'completed' && <p role="alert">资源转换尚未完成，历史记录已保留。<Button onClick={() => void post('/api/resources/migration/retry', {}).then(() => state.refresh()).catch(reason => setActionError(reason.message))} label={"重试转换"} /></p>}
    {state.data.cleanups?.map(item => <p role="status" key={item.request_id}>有一项资源删除后的清理尚未完成。<Link to={`/resources/${item.resource_id}`}>查看历史资源</Link><Button onClick={() => void post(`/api/resources/cleanup/${item.request_id}`, {}).then(() => state.refresh()).catch(reason => setActionError(reason.message))} label={"重试清理"} /></p>)}
    <div className="resource-filters"><TextInput label={"搜索资源"} value={search} onChange={value => setSearch(value)} placeholder="名称或模型"  /><Selector label={"用途"} value={purpose} onChange={value => setPurpose(value)} options={[{value:"",label:"全部"},...Object.entries(purposes).map(([id, label]) => ({value:id,label:(label)}))]} width="100%"  /><Selector label={"状态"} value={status} onChange={value => setStatus(value)} options={[{value:"",label:"全部"},...Object.entries(states).map(([id, label]) => ({value:id,label:(label)}))]} width="100%"  /></div>
    <div className="resource-list">{filtered.map(r => <article className="resource-row" key={r.resource_id}><div><Link to={`/resources/${r.resource_id}`}><strong>{r.name}</strong></Link><small>{kinds[r.kind]} · {r.config.model || '尚未选择模型'} · {r.config.endpoint || '本机'}</small><ResourceStatus resource={r} /></div><Link to={`/resources/${r.resource_id}#projects`}>{r.projects.length} 个项目</Link></article>)}</div>
    {!filtered.length && <div className="empty-state"><strong>{state.data.resources.length ? '没有符合条件的资源' : '还没有添加资源'}</strong><p>项目需要语音识别、内容分析和审阅能力。</p>{state.data.resources.length > 0 && <Button onClick={() => { setSearch(''); setPurpose(''); setStatus(''); }} label={"清除筛选"} />}</div>}
  </section>;
}

function ResourceLink({ href = '', ...props }: Omit<React.ComponentProps<typeof Link>, 'to'> & { href?: string }) { return <Link {...props} to={href} />; }

function ResourceStatus({ resource }: { resource: Resource }) { return <p role="status">{resource.config.purposes.map(p => `${purposes[p]}：${states[resource.validation[p]?.state || 'pending']}`).join(' · ')}</p>; }

function ResourceDetail({ resourceId }: { resourceId: string }) {
  const location = useLocation(); const state = usePolling(signal => api<{ resource: Resource }>(`/api/resources/${resourceId}`, {}, signal), 10000, resourceId); const [deleting, setDeleting] = useState(false);
  if (!state.data) return state.loading ? <LoadingState /> : <ErrorState message={state.error} retry={() => void state.refresh()} />;
  const r = state.data.resource; const back = resourceReturn(location.search);
  return <section className="page"><PageHeading title={r.name} eyebrow={kinds[r.kind]} description={r.deleted ? '资源已删除，历史记录保持可查看。' : r.config.model || '尚未准备模型'} actions={!r.deleted && <><Button  label={"编辑配置"} href={`/resources/${resourceId}/edit${location.search}`} as={ResourceLink} /><Button onClick={() => setDeleting(true)} label={"删除资源"} variant="destructive" /></>} />
    {state.error && <p role="alert">显示的是上次读取结果。{state.error}</p>}<ResourceStatus resource={r} />
    <dl className="summary-list"><div><dt>服务地址</dt><dd>{r.config.endpoint || '本机执行'}</dd></div><div><dt>凭据</dt><dd>{r.has_credential ? '已配置' : '未配置'}</dd></div><div><dt>生效修订</dt><dd>{r.revision}</dd></div></dl>
    <dl className="summary-list">{Object.entries({ provider: '供应商', region: '地域', workspace: '业务空间', language: '识别语言', model_source: '模型来源', timeout_seconds: '请求超时（秒）', request_attempts: '连接重试上限', retry_delay_seconds: '重试间隔（秒）', temperature: '审阅采样温度', max_tokens: '审阅输出上限', command_timeout_minutes: '本地审阅超时（分钟）' }).map(([key, label]) => r.config[key] !== undefined && <div key={key}><dt>{label}</dt><dd>{String(r.config[key]) || '尚未填写'}</dd></div>)}</dl>
    <section><h2>最近用途验证</h2>{r.config.purposes.map(p => <p key={p}>{purposes[p]}：{states[r.validation[p]?.state || 'pending']} · {r.validation[p]?.checked_at ? new Date(r.validation[p].checked_at!).toLocaleString() : '尚未验证'}{r.validation[p]?.code && ` · ${validationMessage(r.validation[p].code)}`}</p>)}</section>
    {r.kind === 'local_asr' && !r.deleted && <ModelPreparation resource={r} refresh={state.refresh} />}
    <section id="projects"><h2>使用它的项目</h2>{r.projects.map(p => <div className="resource-row" key={p.project_id}><span>{p.name} · {p.purposes.map(v => purposes[v]).join('、')}</span><Button  label={"调整分配"} href={`/projects/${p.project_id}?dialog=project-settings&resourceReturn=${resourceId}`} as={ResourceLink} /></div>)}{!r.projects.length && <p>尚未分配给项目</p>}</section>
    <div className="resource-actions"><Button  label={"返回资源"} href={"/resources"} as={ResourceLink} />{back && <Button  label={(new URLSearchParams(location.search).get('origin') === 'onboarding' ? '返回首次设置' : '返回项目')} href={back} as={ResourceLink} />}</div>
    {deleting && <DeleteResource resource={r} close={() => setDeleting(false)} />}
  </section>;
}

function ModelPreparation({ resource, refresh }: { resource: Resource; refresh(): Promise<unknown> }) {
  const [busy, setBusy] = useState(false); const [message, setMessage] = useState(''); const [jobId, setJobId] = useState(resource.preparation?.id || '');
  const job = usePolling(signal => jobId ? api<{ job: { status: string; error?: string; result?: { message?: string } } }>(`/api/jobs/${jobId}`, {}, signal) : Promise.resolve({ job: { status: '', error: '' } }), 2000, `model-${jobId}`);
  const running = job.data?.job.status === 'running' || !!resource.preparation;
  useEffect(() => { if (job.data?.job.status && job.data.job.status !== 'running') void refresh(); }, [job.data?.job.status]);
  const start = async () => { setBusy(true); try { const result = await post<{ job: { id: string } }>(`/api/resources/${resource.resource_id}/prepare`, { expected_revision: resource.revision }); setJobId(result.job.id); setMessage('准备任务已受理，离开页面后会继续。'); await refresh(); } catch (e) { setMessage((e as Error).message); } finally { setBusy(false); } };
  const files = resource.model_files; const percent = files?.bytes_total ? Math.min(100, Math.round((files.installed_bytes || files.bytes_downloaded) / files.bytes_total * 100)) : 0;
  return <section><h2>本机模型</h2><p>下载、校验完整性并使用内置音频验证加载能力，全部通过后才可用。</p>{files && <><p>已安装 {(files.installed_bytes / 1024 ** 3).toFixed(2)} GiB · 已下载 {(files.partial_bytes / 1024 ** 3).toFixed(2)} GiB</p>{running && <progress aria-label="模型准备进度" max={100} value={percent} />}</>}<Button isLoading={busy || running} isDisabled={busy || running} onClick={() => void start()} label={(running ? '正在准备模型…' : resource.ready ? '重新检查模型' : files?.partial_bytes ? '继续准备模型' : '准备模型')} /><p role="status">{job.data?.job.status === 'succeeded' ? '模型准备已通过' : job.data?.job.result?.message || job.data?.job.error || message || (files?.last_error ? '上次下载或完整性校验未完成，已下载文件保留，可继续准备。' : '')}</p>{job.error && <p role="alert">进度暂时无法确认：{job.error}</p>}</section>;
}

function DeleteResource({ resource, close }: { resource: Resource; close(): void }) {
  const navigate = useNavigate(); const state = usePolling(signal => api<{ preview: { can_delete: boolean; resource: Resource; projects: Resource['projects']; active_runs: Resource['active_runs']; failed_runs: Resource['failed_runs']; tasks: string[]; model_files: { can_clean: boolean; shared: boolean; bytes: number } } }>(`/api/resources/${resource.resource_id}/delete-preview`, {}, signal), 15000, `delete-${resource.resource_id}`);
  const [cleanModel, setCleanModel] = useState(false); const [cleanup, setCleanup] = useState<{ cleanup_state: string; cleanup_errors: string[] } | null>(null);
  const [uncertain, setUncertain] = useState(false); const [confirmed, setConfirmed] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const id = useRef(requestId('resource-delete'));
  const preview = state.data?.preview;
  const acceptDeleted = (result: { cleanup_state: string; cleanup_errors: string[] }) => { setUncertain(false); if (result.cleanup_state !== 'completed') setCleanup(result); else navigate('/resources', { replace: true }); };
  const recover = async () => { if (busy) return; setBusy(true); try { const operation = await api<{ result: { cleanup_state: string; cleanup_errors: string[] } | null }>(`/api/resources/operations/${id.current}`); if (operation.result) acceptDeleted(operation.result); else setError('删除结果尚未确认，请继续查询原操作。'); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } };
  const remove = async () => {
    if (busy || uncertain || !preview?.can_delete || state.error || (preview.failed_runs.length && !confirmed)) return;
    setBusy(true); setError('');
    try { const deleted = await api<{ result: { cleanup_state: string; cleanup_errors: string[] } }>(`/api/resources/${resource.resource_id}`, { method: 'DELETE', body: JSON.stringify({ request_id: id.current, expected_revision: resource.revision, acknowledge_failed: confirmed, clean_model: cleanModel && preview.model_files.can_clean }) }); acceptDeleted(deleted.result); }
    catch (e) { const known = e instanceof ApiError && e.status >= 400 && e.status < 500 && e.status !== 408 && e.code !== 'invalid_response'; setUncertain(!known); setError((e as Error).message); if (known) { setConfirmed(false); await state.refresh(); } }
    finally { setBusy(false); }
  };
  return <DialogFrame alert title={`删除“${resource.name}”？`} description="历史成片和记录保留。提交时会再次核对引用与占用。" onClose={close} closeDisabled={busy || uncertain} footer={<><Button isDisabled={busy || uncertain} onClick={close} label={"返回"} /><Button isDisabled={busy || uncertain} onClick={() => void state.refresh()} label={"重新检查"} />{uncertain && <Button isLoading={busy} isDisabled={busy} onClick={() => void recover()} label="查询删除结果" />}{preview?.can_delete && !cleanup && !uncertain && <Button isLoading={busy} isDisabled={busy || Boolean(state.error) || (!!preview.failed_runs.length && !confirmed)} onClick={() => void remove()} label={(busy ? '正在确认删除结果…' : '删除资源')} variant="destructive" />}</>}>
    {cleanup && <section role="alert"><p>资源已删除，清理尚未完成：{cleanup.cleanup_errors.join('、')}。历史记录保留。</p><Button isDisabled={busy} onClick={() => { setBusy(true); post<{ result: typeof cleanup }>(`/api/resources/cleanup/${id.current}`, {}).then(value => { if (value.result?.cleanup_state === 'completed') navigate('/resources', { replace: true }); else setCleanup(value.result); }).catch(reason => setError(reason.message)).finally(() => setBusy(false)); }} label={"重试清理"} /></section>}{(state.error || error) && <p role="alert">{error || state.error}</p>}{!preview ? <LoadingState /> : <>{preview.projects.map(p => <p key={p.project_id}>{p.name} · {p.purposes.map(v => purposes[v]).join('、')} <Link aria-disabled={busy || uncertain || undefined} onClick={event => { if (busy || uncertain) event.preventDefault(); }} to={`/projects/${p.project_id}?dialog=project-settings&resourceReturn=${resource.resource_id}`}>调整分配</Link></p>)}{preview.active_runs.map(r => <p key={r.run_id}>记录正在占用资源：<Link aria-disabled={busy || uncertain || undefined} onClick={event => { if (busy || uncertain) event.preventDefault(); }} to={`/projects/${r.project_id}/runs/${r.run_id}`}>{r.run_id}</Link></p>)}{preview.tasks.length > 0 && <p>资源有 {preview.tasks.length} 项准备或验证任务正在执行，请完成后重试。</p>}{resource.kind === 'local_asr' && <CheckboxInput label={"同时清理专属本机模型（" + " " + ((preview.model_files.bytes / 1024 ** 3).toFixed(2)) + " " + "GiB）" + " " + (preview.model_files.shared ? '：被其他资源共享，需保留' : '')} isDisabled={busy || uncertain || !preview.model_files.can_clean} value={cleanModel && preview.model_files.can_clean} onChange={value => setCleanModel(value)}  />}{preview.failed_runs.length > 0 && <><p>以下失败记录将无法使用此资源继续处理；仍可保留旧结果并显式新建重跑。</p>{preview.failed_runs.map(r => <p key={r.run_id}><Link aria-disabled={busy || uncertain || undefined} onClick={event => { if (busy || uncertain) event.preventDefault(); }} to={`/projects/${r.project_id}/runs/${r.run_id}`}>{r.run_id}</Link></p>)}<CheckboxInput label={"我知道这些记录将无法使用此资源继续处理"} isDisabled={busy || uncertain} value={confirmed} onChange={value => setConfirmed(value)}  /></>}<p>{resource.kind === 'local_asr' ? '默认保留本机模型文件，后续添加可复用。' : '仅删除 Venus 中的配置，不删除服务商账号或远端模型。'}</p></>}
  </DialogFrame>;
}

function ResourceEditor({ resourceId }: { resourceId?: string }) {
  const navigate = useNavigate(); const location = useLocation(); const draftId = useRef(new URLSearchParams(location.search).get('draft') || requestId('draft')); const draftKey = `venus.resource-draft.${resourceId || draftId.current}`;
  const [proposal, setProposal] = useState<Proposal>(() => readDraft(draftKey)?.proposal || (new URLSearchParams(location.search).get('purpose') === 'asr' ? { name: '', kind: 'local_asr', config: { purposes: ['asr'], model_source: 'modelscope' } } : empty())); const [current, setCurrent] = useState<Resource | null>(null); const credentialRef = useRef<HTMLInputElement>(null); const credentialID = useId(); const [credentialVersion, setCredentialVersion] = useState(0); const credential = credentialRef.current?.value || ''; const clearCredential = () => { if (credentialRef.current) credentialRef.current.value = ''; setCredentialVersion(v => v + 1); }; const [visible, setVisible] = useState(false); const [loaded, setLoaded] = useState(!resourceId);
  const [providers, setProviders] = useState<Array<{ id: string; name: string; endpoint?: string; help: string }>>([]); const [regions, setRegions] = useState<Record<string, string>>({}); const [models, setModels] = useState<Array<{ id: string; display_name: string; size_note: string }>>([]);
  const [validation, setValidation] = useState<{ validation_id: string; results: Resource['validation']; content: string } | null>(null); const [busy, setBusy] = useState(''); const [error, setError] = useState(''); const [leaving, setLeaving] = useState(false); const submitId = useRef(readDraft(draftKey)?.operation || requestId('resource-save')); const baseRevision = useRef(readDraft(draftKey)?.revision); const allowLeave = useRef(false); const requestContent = useRef(''); const validationOperation = useRef(readDraft(draftKey)?.validationOperation || ''); const testedContent = useRef('');
  useEffect(() => { const controller = new AbortController(); api<{ providers: typeof providers; regions: typeof regions }>('/api/resources/providers', {}, controller.signal).then(v => { setProviders(v.providers); setRegions(v.regions); }).catch(e => setError(e.message)); api<{ models: typeof models }>('/api/asr/models', {}, controller.signal).then(v => setModels(v.models)).catch(e => setError(e.message)); if (resourceId) api<{ resource: Resource }>(`/api/resources/${resourceId}`, {}, controller.signal).then(v => { setCurrent(v.resource); if (baseRevision.current === undefined) baseRevision.current = v.resource.revision; if (!readDraft(draftKey)) setProposal({ name: v.resource.name, kind: v.resource.kind, config: v.resource.config }); setLoaded(true); }).catch(e => setError(e.message)); return () => controller.abort(); }, [resourceId, draftKey]);
  useEffect(() => { if (loaded) localStorage.setItem(draftKey, JSON.stringify({ proposal, revision: baseRevision.current, operation: submitId.current, validationOperation: validationOperation.current })); }, [proposal, loaded, draftKey]);
  const [previewConfig, setPreviewConfig] = useState<Config | null>(null); const [availableModels, setAvailableModels] = useState<string[]>([]); const [existingResources, setExistingResources] = useState<Resource[]>([]);
  useEffect(() => { if (!resourceId) api<{ resources: Resource[] }>('/api/resources').then(value => setExistingResources(value.resources)).catch(() => undefined); }, [resourceId]);
  useEffect(() => { setPreviewConfig(null); if (!proposal.name || proposal.kind !== 'ai') return; const controller = new AbortController(); api<{ proposal: Proposal }>('/api/resources/preview', { method: 'POST', body: JSON.stringify({ proposal }) }, controller.signal).then(result => setPreviewConfig(result.proposal.config)).catch(() => undefined); return () => controller.abort(); }, [proposal]);
  const discover = async () => { if (busy) return; const tested = content; setBusy('models'); setError(''); try { const result = await post<{ models: string[] }>('/api/resources/models', { proposal, credential: credentialRef.current?.value || undefined, resource_id: resourceId, revision: current?.revision }); if (contentRef.current !== tested) return; setAvailableModels(result.models); if (!result.models.length) setError('未返回模型列表，可继续手动填写。'); } catch { setError('模型列表不可用，可继续手动填写并验证用途。'); } finally { setBusy(''); } };
  const content = JSON.stringify([proposal.kind, proposal.config, credentialVersion]); const contentRef = useRef(content); contentRef.current = content;
  const change = (next: Proposal) => { setProposal(next); setAvailableModels([]); setError(''); };
  const field = (key: string, value: unknown) => change({ ...proposal, config: { ...proposal.config, [key]: value } });
  const selectKind = (kind: Kind) => { clearCredential(); setValidation(null); change({ name: proposal.name, kind, config: { purposes: kind === 'ai' ? ['analysis', 'review'] : kind === 'local_agent' ? ['review'] : ['asr'], ...(kind === 'local_asr' ? { model_source: 'modelscope', language: 'zh' } : {}) } }); };
  const selectProvider = (provider: string) => { clearCredential(); setValidation(null); change({ ...proposal, config: { purposes: proposal.config.purposes, provider, model: '', endpoint: providers.find(p => p.id === provider)?.endpoint || '' } }); };
  const numericInvalid = Object.values(proposal.config).some(v => v === null);
  const test = async () => { if (busy || numericInvalid) return;
    setBusy('test'); setError('');
    try {
      if (validationOperation.current) {
        const prior = await api<{ result: { validation_id?: string; results?: Resource['validation']; state?: string } | null }>(`/api/resources/operations/${validationOperation.current}`);
        if (prior.result && !prior.result.validation_id) { setError('上次验证结果尚未确认，请稍后查询原操作；不会重复发起验证。'); return; }
        if (prior.result?.validation_id) {
        if (testedContent.current === contentRef.current) setValidation({ validation_id: prior.result.validation_id, results: prior.result.results!, content: testedContent.current });
        else setError('上次验证已完成。当前配置或密钥已变化，请重新验证当前内容。');
        validationOperation.current = ''; return;
        }
      }
      validationOperation.current ||= requestId('resource-validate'); testedContent.current = content;
      localStorage.setItem(draftKey, JSON.stringify({ proposal, revision: baseRevision.current, operation: submitId.current, validationOperation: validationOperation.current }));
      const result = await post<{ validation_id: string; results: Resource['validation'] }>('/api/resources/validate', { request_id: validationOperation.current, proposal, credential: credentialRef.current?.value || undefined, resource_id: resourceId, revision: current?.revision, purposes: proposal.config.purposes });
      validationOperation.current = '';
      if (contentRef.current === testedContent.current) setValidation({ ...result, content: testedContent.current });
    } catch (e) {
      if (e instanceof ApiError && e.status >= 400 && e.status < 500 && e.status !== 408 && e.code !== 'validation_result_unknown' && e.code !== 'invalid_response') validationOperation.current = '';
      setError((e as Error).message);
    } finally {
      localStorage.setItem(draftKey, JSON.stringify({ proposal, revision: baseRevision.current, operation: submitId.current, validationOperation: validationOperation.current })); setBusy('');
    }
  };

  const back = () => { clearCredential(); allowLeave.current = true; if (blocker.state === 'blocked') blocker.proceed(); else navigate(resourceReturn(location.search) || (resourceId ? `/resources/${resourceId}` : '/resources')); };
  const saved = (r: Resource) => { allowLeave.current = true; localStorage.removeItem(draftKey); clearCredential(); navigate(resourceReturn(location.search, r) || `/resources/${r.resource_id}`, { replace: true }); };
  const save = async () => { if (busy || numericInvalid || !proposal.name.trim()) return; setBusy('save'); setError(''); const payload = { proposal, credential: credentialRef.current?.value || undefined, expected_revision: baseRevision.current, validation_id: validation?.content === content ? validation.validation_id : undefined }; const encoded = JSON.stringify(payload); if (requestContent.current && requestContent.current !== encoded) { setError('上次保存结果尚未确认，请恢复原内容后重试，或刷新查询原操作结果。'); setBusy(''); return; } requestContent.current = encoded; localStorage.setItem(draftKey, JSON.stringify({ proposal, revision: baseRevision.current, operation: submitId.current, validationOperation: validationOperation.current })); try { const result = await api<{ resource: Resource }>(resourceId ? `/api/resources/${resourceId}` : '/api/resources', { method: resourceId ? 'PATCH' : 'POST', body: JSON.stringify({ ...payload, request_id: submitId.current }) }); saved(result.resource); } catch (e) { try { const operation = await api<{ result: Resource | null }>(`/api/resources/operations/${submitId.current}`); if (operation.result) { saved(operation.result); return; } } catch { /* Keep the same operation identity until its result is known. */ } if (e instanceof ApiError && e.status >= 400 && e.status < 500 && e.status !== 408 && e.code !== 'invalid_response') { requestContent.current = ''; submitId.current = requestId('resource-save'); localStorage.setItem(draftKey, JSON.stringify({ proposal, revision: baseRevision.current, operation: submitId.current, validationOperation: validationOperation.current })); } if (resourceId && e instanceof ApiError && e.code === 'revision_conflict') { try { const latest = await api<{ resource: Resource }>(`/api/resources/${resourceId}`); setCurrent(latest.resource); } catch { /* Keep the draft until comparison is possible. */ } } setError((e as Error).message); } finally { setBusy(''); } };
  const dirty = Boolean(credential || (current ? proposal.name !== current.name || JSON.stringify(proposal.config) !== JSON.stringify(current.config) : proposal.name || proposal.config.model));
  const unresolved = !!requestContent.current;
  const blocker = useBlocker(({ nextLocation }) => !allowLeave.current && (dirty || !!busy || unresolved) && nextLocation.pathname !== location.pathname);
  useBeforeUnload(event => { if (dirty && !allowLeave.current) event.preventDefault(); });
  useEffect(() => { if (!resourceId && !new URLSearchParams(location.search).get('draft')) { const query = new URLSearchParams(location.search); query.set('draft', draftId.current); navigate({ pathname: location.pathname, search: query.toString() }, { replace: true }); } }, [resourceId, location.pathname, location.search, navigate]);
  useEffect(() => { const pending = readDraft(draftKey)?.operation; if (pending) api<{ result: Resource | null }>(`/api/resources/operations/${pending}`).then(value => { if (value.result) saved(value.result); }).catch(() => setError('暂时无法确认上次操作结果，请稍后重试。')); }, [draftKey]);
  if (!loaded) return error ? <ErrorState message={error} retry={() => window.location.reload()} /> : <LoadingState />;
  const similar = existingResources.filter(r => r.kind === proposal.kind && r.config.model && r.config.model === proposal.config.model && (r.config.endpoint || '') === (previewConfig?.endpoint || proposal.config.endpoint || ''));
  const unchanged = current && proposal.name === current.name && JSON.stringify(proposal.config) === JSON.stringify(current.config) && !credential && validation?.content !== content;
  const renamed = current && proposal.name !== current.name && JSON.stringify(proposal.config) === JSON.stringify(current.config) && !credential && validation?.content !== content;
  const verified = validation?.content === content; const anyReady = verified && Object.values(validation.results).some(v => v.state === 'ready');
  return <section className="page resource-editor"><PageHeading title={current ? `编辑“${current.name}”` : '添加资源'} description={current ? '这是一项共享资源；更改仅影响引用项目的新记录。' : '添加后在项目中明确选择，不会自动开始处理。'} />
    {current?.deleted && <p role="alert">原资源已删除，此草稿不能提交到原对象。</p>}{error && <p className="form-error" role="alert">{error}</p>}{current && baseRevision.current !== current.revision && <section role="alert"><p>资源已在其他位置修改。当前模型：{current.config.model}；草稿模型：{proposal.config.model}。请比较后继续。</p><Button onClick={() => { baseRevision.current = current.revision; setValidation(null); setError('已采用最新修订作为比较基线，请重新验证草稿。'); }} label={"已比较，继续编辑草稿"} /></section>}
    {!!similar.length && <section role="status"><p>已有使用相同模型和服务地址的资源。请确认是否可以复用；不同账号可以分别保存。</p>{similar.map(r => <Button key={r.resource_id} label={(r.name) + " " + "· 查看或选择"} href={resourceReturn(location.search, r) || `/resources/${r.resource_id}`} as={ResourceLink} />)}</section>}
    <form className="resource-form" onSubmit={e => { e.preventDefault(); void save(); }}><FormLayout className="resource-fields">
      <TextInput label={"资源名称"} isRequired  value={proposal.name} onChange={value => change({ ...proposal, name: value.slice(0, 80) })}  />
      <Selector label={"资源类型"} isDisabled={!!current} value={proposal.kind} onChange={value => selectKind(value as Kind)} options={[...Object.entries(kinds).filter(([kind]) => { const purpose = new URLSearchParams(location.search).get('purpose'); return !purpose || (purpose === 'asr' ? kind.includes('asr') : purpose === 'analysis' ? kind === 'ai' : kind === 'ai' || kind === 'local_agent'); }).map(([id, name]) => ({value:id,label:(name)}))]} width="100%"  />
      {proposal.kind === 'ai' && <><Selector label={"供应商"} value={proposal.config.provider || ''} onChange={value => selectProvider(value)} options={[{value:"",label:"请选择供应商"},...providers.map(p => ({value:p.id,label:(p.name)}))]} width="100%"  />{providers.find(p => p.id === proposal.config.provider)?.help && <p>{providers.find(p => p.id === proposal.config.provider)?.help}</p>}{proposal.config.provider === 'qwen' && <><Selector label={"地域"} value={proposal.config.region || ''} onChange={value => { clearCredential(); change({ ...proposal, config: { ...proposal.config, region: value, workspace: '', endpoint: '', model: '' } }); }} options={[{value:"",label:"请选择地域"},...Object.entries(regions).map(([id, name]) => ({value:id,label:(name)}))]} width="100%"  /><TextInput label={"业务空间 ID"} value={proposal.config.workspace || ''} onChange={value => { clearCredential(); change({ ...proposal, config: { ...proposal.config, workspace: value, endpoint: '', model: '' } }); }}  /></>}</>}
      {proposal.kind === 'ai' && proposal.config.provider !== 'custom' && <p>最终服务地址：{previewConfig?.endpoint || (proposal.config.provider ? '填写地域与业务空间后显示' : '请先选择供应商')}</p>}
      {(proposal.kind === 'cloud_asr' || proposal.kind === 'ai' && proposal.config.provider === 'custom') && <TextInput label="服务地址" description="修改目标地址后请重新输入密钥。" value={proposal.config.endpoint || ''} onChange={value => { clearCredential(); field('endpoint', value); }}  />}
      {proposal.kind === 'local_asr' ? <><Selector label={"模型"} value={proposal.config.model || ''} onChange={value => field('model', value)} options={[{value:"",label:"请选择模型"},...models.map(m => ({value:m.id,label:(m.display_name) + " " + "·" + " " + (m.size_note)}))]} width="100%"  /><Selector label={"下载来源"} value={proposal.config.model_source || 'modelscope'} onChange={value => field('model_source', value)} options={[{value:"modelscope",label:"ModelScope"},{value:"huggingface",label:"Hugging Face"}]} width="100%"  /></> : proposal.kind !== 'local_agent' && <TextInput label={"模型标识"} value={proposal.config.model || ''} onChange={value => field('model', value)}  />}
      {(proposal.kind === 'ai' || proposal.kind === 'cloud_asr') && <>{!!availableModels.length && <Selector label="可用模型" placeholder="选择查询到的模型，也可手动填写" value={proposal.config.model || ''} options={availableModels} onChange={value => field('model', value)} width="100%" />}<Button type="button" isLoading={busy === 'models'} isDisabled={!!busy || !proposal.name} onClick={() => void discover()} label={(busy === 'models' ? '正在查询模型…' : '获取模型列表')} /><small>只在点击时查询当前连接；候选模型仍需验证用途，也可直接手填。</small></>}
      {(proposal.kind === 'ai' || proposal.kind === 'cloud_asr' || proposal.kind === 'local_asr' && proposal.config.model_source === 'huggingface') && <Field inputID={credentialID} descriptionID={`${credentialID}-description`} label={proposal.kind === 'local_asr' ? 'HF 下载凭据（可选）' : 'API Key'} description={current?.has_credential ? '已配置；同一地址留空表示保留。未保存密钥不会写入草稿。' : '未提交密钥不会保存到草稿，离开后需重新输入。'} width="100%"><div className="resource-credential"><input ref={credentialRef} id={credentialID} className="form-control" aria-describedby={`${credentialID}-description`} autoComplete="off" type={visible ? 'text' : 'password'} onChange={() => { setAvailableModels([]); setCredentialVersion(v => v + 1); }} /><Button type="button" onClick={() => setVisible(!visible)} label={visible ? '隐藏本次输入' : '显示本次输入'} /></div></Field>}
      {(proposal.kind === 'local_asr' || proposal.kind === 'cloud_asr') && <Selector label={"识别语言"} value={proposal.config.language || 'zh'} onChange={value => field('language', value)} options={[{value:"zh",label:"中文"},{value:"en",label:"英语"},{value:"auto",label:"自动识别"}]} width="100%"  />}
      {proposal.kind === 'ai' && <details><summary>高级请求与审阅参数</summary>{([['timeout_seconds', '请求超时（秒）', 300, 30, 3600], ['request_attempts', '连接建立尝试次数', 1, 1, 10], ['retry_delay_seconds', '连接重试间隔（秒）', 3, 0, 60], ['max_tokens', '审阅输出 Token 上限', 4096, 512, 32000]] as const).map(([key, label, fallback, min, max]) => <NumberInput label={(label)} min={min} max={max} value={proposal.config[key] === null ? null : Number(proposal.config[key] ?? fallback)} onChange={value => field(key, value)} status={proposal.config[key] === null ? { type: "error", message: "请填写数值" } : undefined} isIntegerOnly hasClear key={key} />)}{previewConfig?.request_profile === 'kimi-k2.6-default' ? <p>该模型使用服务端默认采样，不发送温度参数。</p> : <NumberInput label={"审阅温度"} min={0} max={2} step={0.1} value={proposal.config.temperature === null ? null : Number(proposal.config.temperature ?? 0.2)} status={proposal.config.temperature === null ? { type: 'error', message: '请填写数值' } : undefined} onChange={value => field('temperature', value)} hasClear  />}<p>只重试确定尚未建立连接的请求。结果未知或输出错误不会重复推理。</p></details>}
      {proposal.kind === 'local_agent' && <details><summary>本地 Agent 参数</summary><NumberInput label={"执行超时（分钟）"} min={1} max={240} value={proposal.config.command_timeout_minutes === null ? null : Number(proposal.config.command_timeout_minutes ?? 60)} status={proposal.config.command_timeout_minutes === null ? { type: 'error', message: '请填写数值' } : undefined} onChange={value => field('command_timeout_minutes', value)} isIntegerOnly hasClear  /><CheckboxInput label={"内联审阅材料"} value={proposal.config.include_review_package_inline !== false} onChange={value => field('include_review_package_inline', value)}  /><p>不会授予 Agent 直接修改项目文件的权限。</p></details>}
      {proposal.kind === 'ai' && <fieldset><legend>用途</legend>{(['analysis', 'review'] as Purpose[]).map(p => <CheckboxInput label={(purposes[p])} value={proposal.config.purposes.includes(p)} onChange={value => field('purposes', value ? [...proposal.config.purposes, p] : proposal.config.purposes.filter(v => v !== p))} key={p} />)}</fieldset>}
      <section><h2>验证用途</h2><p>将使用内置测试内容；云端调用或本地 Agent 可能产生少量费用。不会发送用户录像。</p><Button type="button" isLoading={busy === 'test'} isDisabled={!!busy || numericInvalid || !proposal.config.purposes.length} onClick={() => void test()} label={(busy === 'test' ? '正在验证用途…' : proposal.kind === 'local_asr' ? '检查模型' : '验证用途')} /><div role="status">{validation && !verified ? <p>配置已更改，请重新验证。</p> : validation && Object.entries(validation.results).map(([p, v]) => <p key={p}>{purposes[p as Purpose]}：{states[v.state]}{v.code && `（${validationMessage(v.code)}）`}</p>)}</div></section>
      {current && <section><h2>保存影响</h2><p>当前模型：{current.config.model || 'Claude Code'} → {proposal.config.model || 'Claude Code'}</p><p>已有排队、处理中和历史记录保留原配置。</p>{current.projects?.map(p => <p key={p.project_id}>{p.name} · {p.purposes.map(v => purposes[v]).join('、')}</p>)}</section>}
      <div className="resource-actions"><Button type="button" isDisabled={!!busy || unresolved} onClick={() => dirty ? setLeaving(true) : back()} label={"返回"} /><Button type="submit" isLoading={busy === 'save'} isDisabled={!!busy || numericInvalid || !!current?.deleted || !!unchanged || !proposal.name.trim() || !proposal.config.purposes.length} label={(busy === 'save' ? '正在确认保存结果…' : renamed ? '保存名称' : anyReady ? current ? '保存资源更改' : '添加资源' : current?.ready ? '保存资源更改' : '保存为待准备资源')} variant="primary" /></div>
    </FormLayout></form>
    {(leaving || blocker.state === 'blocked') && <DialogFrame closeDisabled={!!busy || unresolved} title="离开配置？" description="非敏感字段可以保留为本机草稿；未提交密钥会清除。" onClose={() => { setLeaving(false); if (blocker.state === 'blocked') blocker.reset(); }} footer={<><Button onClick={() => { setLeaving(false); if (blocker.state === 'blocked') blocker.reset(); }} label={"继续编辑"} /><Button onClick={() => { localStorage.removeItem(draftKey); clearCredential(); back(); }} isDisabled={!!busy || unresolved} label={"放弃修改"} /><Button onClick={() => { clearCredential(); back(); }} isDisabled={!!busy || unresolved} label={"保留草稿并离开"} variant="primary" /></>}><p>正式配置保持不变。</p></DialogFrame>}
  </section>;
}
